---
title: "DATA605 w12"
author: "Richard"
date: "4/25/2021"
output: html_document
---

# loading packages

```{r}
library(tidyverse)
```

# loading dataset

```{r}
url="https://raw.githubusercontent.com/schoolkidrich/R/main/DATA_605/week12/who.csv"

who=read.csv(url)
summary(who)
```

# 1

#### scatterplot LifeExp~TotExp

```{r}
# scatter plot represents a log relationship rather than a linear one
who%>%
  ggplot(aes(x=TotExp,y=LifeExp))+geom_point(stat='identity')

```

#### model 1

```{r}
m1 = lm(LifeExp~TotExp,who)
summary(m1)
```

#### I do not believe assumptions for linear regression are currently met

```{r}

# residuals do not cluster around 0
plot(fitted(m1),resid(m1))

# residuals do not seem normally distributed 
qqnorm(resid(m1))

```


# 2 log transform for LifeExp and TotExp

#### scatter plot

```{r}
who%>%
  ggplot(aes(x = LifeExp^4.6,y=TotExp^0.06))+geom_point()
```


#### model 2

```{r}
m2 = lm(I(LifeExp^4.6)~I(TotExp^0.06), who)
summary(m2)
```

#### model 2 is "better" as it fits more assumptions and boasts a R^2 value closer to one.

```{r}

# residuals cluster around 0
plot(fitted(m2),resid(m2))

# residual for model 2 is closer to normal than model 1 
qqnorm(resid(m2))
```


# 3

#### model 2 predictions 

```{r}
# accounting for 0.06 exponent for TotExp
TotExpPredict = data.frame(TotExp=c(1.5^(1/0.06),2.5^(1/0.06)))
TotExpPredict$prediction = predict(m2,TotExpPredict)

# accounting for 4.6 exponent for LifeExp
TotExpPredict$prediction = TotExpPredict$prediction^(1/4.6)
head(TotExpPredict)

```

# 4

#### model 3

```{r}
m3 = lm(LifeExp~PropMD+TotExp+PropMD*TotExp,who)
summary(m3)
```

#### model 3 does not seem to be very good

```{r}
# residuals form a pattern
plot(fitted(m3),resid(m3))

# residual for is not normally distributed
hist(resid(m3))
```


# 5

```{r}
forecast = data.frame(PropMD = c(0.03),TotExp = c(14))
forecast$prediction = predict(m3,forecast)

# this prediction does not seem realistic as the predicted value is high for a low TotExp value.
head(forecast)
```

