---
title: "data605 hw13"
author: "Richard"
date: "5/2/2021"
output: html_document
---
# libraries

```{r}
library(tidyverse)
```

 
# 1 solve: integral(4e^(-7x))dx

- => integral(4e^(-7x))(-1/7)d(-7x)
- => (-1/7)4e^(-7x)
- => (-4/7)e&(-7x)

# 2 dN/dt = -3150(t^-4)-200    (t=1 ->  6530)

- => integral((-3150/t^4)-200)dt = (3150/(3t^3))-200t+c
- => (t = 1) => 3150/3-200+c = 6530 => c = 6530 - 850 = 5680
- => N(t) = 3150/(3t^3)-200t+5680

# 3 f(x) = 2x-9

```{r}
formula = function(x){
  return (2*x-9)
}

xval = seq(4.5,8.5,1)
yval = formula(xval)

area = 0
for (i in seq(length(xval))){
  area = area+ yval[i]
}

area
```

# 4 y = x^2-2x-2, y= x+2

```{r}
# y = x^2-2x-2
formula1 = function(x){
  return(x^2-2*x-2)
}
# y = x+2
formula2 = function(x){
  return(x+2)
}

x = seq(-2,5,0.01)

y1 = formula1(x)
y2 = formula2(x)

points = data.frame(x,y1,y2)
# we can see from the chart that the area is between -1 and 4 with y=x+2 being greater
points%>%
  ggplot(aes(x=x))+geom_line(aes(y=y1))+geom_line(aes(y=y2))

area_btwn = 0

for (i in seq(-1,4,0.01)){
  area_btwn = area_btwn + (formula2(i)-formula1(i))*0.01
}

# area ~ 20.833
area_btwn
```

# 5 y = 8.25x + 3.75*0.5*110/x

- => y = 8.25x + 206.25(x^-1)
- => dy/dx = 8.25-206.25(x^-2)
- => 0 = 8.25-206.25(x^-2)
- => x^2 = 206.25/8.25 = 25
- => x = 5, lot = 110/x = 110/5 = 22


# 6 integral(ln(9x)*x^6)dx

- => integral(f(x)g'(x))dx = f(x)g(x) - integral(f'(x)g(x))dx
- => let f(x) = ln(9x) and g'(x) = x^6
- => f'(x) = 1/x and g(x) = x^7/7
- => ln(9x)*((x^7)/7) - integral(x^6/7)dx
- => ln(9x)*((x^7)/7) - (x^7)/49 + c
- => (x^7(7ln(9x)-1))/49 + c

# 7 f(x) = 1/6x interval: [1,e^6]

- => integral(1/6x)dx = (1/6)*ln(x)
- => (1/6)ln(e^6) - (1/6)ln(1)
- => (1/6)*6ln(e) - 0
- => ln(e) = 1
- => 1/6x is PDF on interval [1,e^6] as area between [0,1] 



