---
title: "hw15"
author: "Richard"
date: "5/16/2021"
output: html_document
---

# 1

```{r}
points = data.frame(x = c(5.6,6.3,7,7.7,8.4),
           y = c(8.8,12.4,14.8,18.2,20.8))
# y = 4.257x - 14.8
lm(y~x, points)
```

# 2 

```
min/ max when slope = 0

f(x,y) = 24x-6xy^2-8y^3

f'x = 24-6y^2
=> 0 = 24-6y^2
=> y^2 = 4 
=> y  = +/-2

f'y = -12xy-24y^2
=> y=2, => 0 = -24x-24(4)
=> x = -4 => x,y = (-4,2)

=> y=-2 => 0= 24x-24(4) 
=> x = 4 => x,y = (4,2)

f'xx = 0
f'yy = -12x-48y
f'xy = -12y

G(x,y) = f'xx*f'yy - f'xy^2 = 0 -(-12y)^2 = -144y^2

since G(x,y) = -144y^2 < 0 => x,y = (-4,2) and (4,2) are saddle points

```

# 3 

```{r}
x = 2.3
y = 4.1

# a 

unit_house = function(x,y){
  return(81-21*x+17*y)
}

unit_name = function(x,y){
  return(40+11*x-23*y)
}

revenue_house = function(x,y){
  units = unit_house(x,y)
  return(x*units)
}

revenue_name = function(x,y){
  units = unit_name(x,y)
  return(y*units)
}

total_revenue = function(x,y){
  return(revenue_house(x,y)+revenue_name(x,y))
}

# b

total_revenue(x,y)
```

# 4 

```
x+y = 96 => x= 96-y

C(x,y) = (1/6)x^2+(1/6)y^2+7x+25y+700

=> (1/6)(96-y)^2+(1/6)y^2+7(96-y)+25y+700
=> (1/3)y^2-14y+2908

c'y = (2/3)y-14
=> 14= (2/3)y
=> y = 21

=> x+y = 96 
=> x+21=96 
=> x = 75
=> x,y = (75,21)


```

#5

```

integral(integral(e^(8x+3y),[2,4]),[2,4])dxdy
=> integral(e^8x,[2,4])dx * integral(e^3y.[2,4])dy
=> ((1/8)e^(8(4)) - (1/8)e^(8(2)))*((1/3)e^(3(4))-(1/3)e^(3(2)))
=> 5.341*10^17

```




