---
title: "EigenShoes"
author: "Richard"
date: "2/21/2021"
output: html_document
---
# Set up
#### Packages

```{r}
library(EBImage)
library(jpeg)
library(OpenImageR)
```

#### Loading Images

```{r}
num=17
path="jpg/"
files=list.files(path,pattern="\\.jpg")[1:num]
```

#### View Images Function

```{r}
height=1200; width=2500;scale=20
plot_jpeg = function(path, add=FALSE)
{ jpg = readJPEG(path, native=T) # read the file
  res = dim(jpg)[2:1] # get the resolution, [x, y]
  if (!add) # initialize an empty plot area if add==FALSE
    plot(1,1,xlim=c(1,res[1]),ylim=c(1,res[2]),asp=1,type='n',xaxs='i',yaxs='i',xaxt='n',yaxt='n',xlab='',ylab='',bty='n')
  rasterImage(jpg,1,1,res[1],res[2])
}
```

#### Loading into Array

```{r}
im=array(rep(0,length(files)*height/scale*width/scale*3), dim=c(length(files), height/scale, width/scale,3))

for (i in 1:num){
  temp=resize(readJPEG(paste0(path, files[i])),height/scale, width/scale)
  im[i,,,]=array(temp,dim=c(1, height/scale, width/scale,3))}
```

#### Vectorizing Images

```{r}
flat=matrix(0, num, prod(dim(im))) 
for (i in 1:num) {
  newim <- readJPEG(paste0(path, files[i]))
  r=as.vector(im[i,,,1]); g=as.vector(im[i,,,2]);b=as.vector(im[i,,,3])
  flat[i,] <- t(c(r, g, b))
}
shoes=as.data.frame(t(flat))
```

# Plots

```{r}
par(mfrow=c(3,3))
par(mai=c(.3,.3,.3,.3))
for (i in 1:num){  #plot the first images only
  plot_jpeg(writeJPEG(im[i,,,]))
}
```

#### Eigencomponents from Correlation Structure

```{r}
scaled=scale(shoes, center = TRUE, scale = TRUE)
mean.shoe=attr(scaled, "scaled:center") #saving for classification
std.shoe=attr(scaled, "scaled:scale") 
```

#### Correlation

```{r}
Sigma_=cor(scaled)
```

#### Getting Eigencomponents

```{r}
myeigen=eigen(Sigma_)
cumsum(myeigen$values) / sum(myeigen$values)
```

#### EigenShoes

```{r}
scaling=diag(myeigen$values[1:5]^(-1/2)) / (sqrt(nrow(scaled)-1))
eigenshoes=scaled%*%myeigen$vectors[,1:5]%*%scaling
imageShow(array(eigenshoes[,1], c(60,125,3)))
```

# Generate Principal Components
#### Transform Images

```{r}
height=1200
width=2500
scale=20
newdata=im
dim(newdata)=c(length(files),height*width*3/scale^2)
mypca=princomp(t(as.matrix(newdata)), scores=TRUE, cor=TRUE)

```

#### Generate New Images

```{r}
mypca2=t(mypca$scores)
dim(mypca2)=c(length(files),height/scale,width/scale,3)
par(mfrow=c(5,5))
par(mai=c(.001,.001,.001,.001))
for (i in 1:num){
  plot_jpeg(writeJPEG(mypca2[i,,,], bg="white")) 
}
```

#### Eigencomponents

```{r}
a=round(mypca$sdev[1:num]^2/ sum(mypca$sdev^2),3)
cumsum(a)
```
#### New Data Set

```{r}
x = t(t(eigenshoes)%*%scaled)
x
```

